parameters:
    okvpn.better_oro: []

services:
    okvpn.message_queue.extension.redeliver_orphan:
        class: Okvpn\Bundle\BetterOroBundle\Extension\RedeliverOrphanMessagesDbalExtension
        arguments: [~]
        tags:
            - { name: oro_message_queue.consumption.extension }

    okvpn_action.run_cron_command:
        class: Okvpn\Bundle\BetterOroBundle\Cron\RunCronCommandAction
        arguments: ['@oro_cron.async.command_runner']

    oro_filter.date_grouping_filter:
        class: Okvpn\Bundle\BetterOroBundle\Filters\DateGroupingFilter
        arguments:
            - '@form.factory'
            - '@oro_filter.filter_utility'
            - '@doctrine'
        tags:
            - { name: oro_filter.extension.orm_filter.filter, type: date_grouping, datasource: orm }

    oro_datagrid.twig.datagrid:
        class: Okvpn\Bundle\BetterOroBundle\Datagrid\DataGridExtension
        public: false
        arguments:
            - '@service_container'
        tags:
            - { name: twig.extension }

    oro_security.listener.context_listener:
        class: Okvpn\Bundle\BetterOroBundle\EventListener\ContextListener
        arguments:
            - '@service_container'
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest, priority: 7 }

    okvpn.form.extension.oro_date_field_choice:
        class: Okvpn\Bundle\BetterOroBundle\Form\Extension\DateFieldChoiceExtension
        tags:
            - { name: form.type_extension, extended_type: 'Oro\Bundle\QueryDesignerBundle\Form\Type\DateFieldChoiceType' }

    oro_asset_bundle.asset_config.cache:
        class: Okvpn\Bundle\BetterOroBundle\Asset\AssetConfigCache
        arguments:
            - '@kernel'
