parameters:
    okvpn.better_oro: []

services:
    okvpn.message_queue.extension.redeliver_orphan:
        class: Okvpn\Bundle\BetterOroBundle\Extension\RedeliverOrphanMessagesDbalExtension
        arguments: [~]
        tags:
            - { name: oro_message_queue.consumption.extension }

    okvpn_action.run_cron_command:
        class: Okvpn\Bundle\BetterOroBundle\Cron\RunCronCommandAction
        arguments: ['@oro_cron.async.command_runner']
