doctrine:
    dbal:
        connections:
            joblog:
                driver:   '%database_driver%'
                host:     '%database_host%'
                port:     '%database_port%'
                dbname:   '%database_name%'
                user:     '%database_user%'
                password: '%database_password%'
                charset:  UTF8

okvpn_better_oro:
    capabilities: []

security:
    firewalls:
        main:
            organization-remember-me:
                secret:                    '%secret%'
                name:                       BAPRM
                lifetime:                   31557600 # 1 year
                httponly:                   true
